# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nuts
email:
description: >- # this means to ignore newlines until "baseurl:"
  Nuts is een nieuw initiatief om 'privacy-by-design' en gedecentraliseerd
  data uit te wisselen in de gezondheidszorg.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "site.distributed.health" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Slack invite link, expires every 30 days. Current link expires on 2023-03-31
slack_invite_url: https://join.slack.com/t/nuts-foundation/shared_invite/zt-1qfkrwpm9-RXREwsmXGpp0bGbONOIx6g

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
